type: object
requires: [
  'telegram_api_token',
  'telegram_group_name',
  'telegram_enable_polling',
  'matrix_room_id',
  'matrix_domain',
  'matrix_homeserver_url'
]
properties:
    telegram_api_token:
        type: string
    telegram_group_name:
        type: string
    telegram_enable_polling:
        type: boolean
    matrix_room_id:
        type: string
    matrix_domain:
        type: string
    matrix_homeserver_url:
        type: string
